#!/usr/bin/env bash
csd="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$csd"

if [[ $(command -v quiterss) == "" ]]; then
pip3 install -r requirements.txt
sudo apt update
sudo apt install quiterss -y   # brew install --cask fluent-reader
fi

sudo docker kill rsshub_python || sudo docker rm rsshub_python || sudo docker run -d --rm --name rsshub_python -p 11201:5000 superkeyor/rsshub_python:latest
echo ""
echo "*******************************************"
echo "flask run at port 1201, docker run at 11201"
echo "*******************************************"
flask run --host=0.0.0.0 --port=1201

