#!/usr/bin/env bash
csd="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$csd"

if [[ /home/parallels/anaconda3/envs/stem/bin/flask == "" ]]; then
pip3 install -r requirements.txt
sudo apt install quiterss -y   # brew install --cask fluent-reader
fi

flask run --host=0.0.0.0 --port=1201   # ipython # to debug
